# Generated by Django 5.1.1 on 2024-09-29 10:14

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must be exactly 7 digits long.', regex='^\\d{7}$')])),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('AI', 'AI'), ('Software Engineering', 'Software Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Management Sciences', 'Management Sciences'), ('Computer Science', 'Computer Science')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('hostel', models.CharField(choices=[('1', 'Hostel 1'), ('2', 'Hostel 2'), ('3', 'Hostel 3'), ('4', 'Hostel 4'), ('5', 'Hostel 5'), ('6', 'Hostel 6'), ('7', 'Hostel 7'), ('8', 'Hostel 8'), ('9', 'Hostel 9'), ('10', 'Hostel 10'), ('11', 'Hostel 11'), ('12', 'Hostel 12')], max_length=2)),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('account_created_at', models.DateTimeField(auto_now_add=True, verbose_name='account created at')),
                ('account_updated_at', models.DateTimeField(auto_now=True, verbose_name='account updated at')),
                ('uni_id_card', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
